##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
#DIRS=Scratch
DIRS=PDG Exclusions Target Partition MTCG RenameBasicBlocks Utilities \
   DependenceRemover MiscProfilers LW SMTAliasAnalysis Negotiator RMT \
   ClangAnnotationExtractor Privatization ISpecLoopPDG AggressiveDepRemover \
   CommutativeSetManager DOALLTransform Analysis BlockLocalVarsManager \
   PTXBackend PTXUtil

include $(LEVEL)/Makefile.common
